#!/bin/bash

LOG="/private/tmp/dlmc-installer.log"
echo "Running postinstall..." >> "$LOG"

/bin/cp -R "/private/tmp/pkg-root/Applications/DLMC Video Downloader.app" "/Applications/" >> "$LOG" 2>&1
/bin/chmod -R 755 "/Applications/DLMC Video Downloader.app" >> "$LOG" 2>&1
/usr/sbin/chown -R root:wheel "/Applications/DLMC Video Downloader.app" >> "$LOG" 2>&1

echo "Postinstall complete." >> "$LOG"
exit 0
